spring:
  application.name: kibit
  datasource:
    url: jdbc:postgresql://postgres:5432/kibit
    username: postgres
    password: kibit
    platform: postgresql
  jpa:
    hibernate.ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: broker:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer